# commented values will not be used

ZeroArgCommand = [
    "GripperOpen",
    "GripperClose" ,
    "ActivateRobot",
    #"ActivateSim" ,
    #"DeactivateSim",
    "ClearMotion",
    "DeactivateRobot",
    "BrakesOn",
    "BrakesOff",
    "Home",
    "PauseMotion",
    "ResetError",
    #"ResetPStop",
    "ResumeMotion",
    #"StopSaving",
    #"SwitchToEtherCAT",
    #"TCPDumpStop" 
]

ZeroArgRequest = [
    "GetFwVersion" ,
    "GetProductType",
    "GetRobotSerial",
    "GetAutoConf",
    "GetAutoConfTurn",
    "GetBlending",
    "GetCartAcc",
    "GetCartAngVel",
    "GetCheckpoint",
    "GetConf",
    "GetConfTurn",
    "GetGripperForce",
    "GetGripperVel",
    "GetJointAcc",
    "GetJointLimitsCfg",
    "GetJointVel",
    "GetMonitoringInterval",
    "GetNetworkOptions",
    "GetRealTimeMonitoring",
    "GetTourqueLimits",
    "GetTourqueLimitsCfg",
    "GetTRF",
    "GetVelTimeout",
    "GetWRF",
    "GetCmdPendingCount",
    # probably will only use this one
    "GetJoints",
    "GetPose",
    "GetRTC",
    "GetRtCartPos",
    "GetRtCartVel",
    "GetRtConf",
    "GetRtConfTurn",
    "GetRtJointPos",
    "GetRtJointTorq",
    "GetRtJointVel",
    "GetRtTargetCartPos",
    "GetRtTargetCartVel",
    "GetRtTargetConf",
    "GetRtTargetConfTurn",
    "GetRtTargetJointPos",
    "GetRtTargetJointVel",
    "GetStatusGripper",
    "GetStatusRobot",
    "GetTorqueLimitsSatus" 
]

OneArgCommand = [
    "Delay",
    "GripperOpen",
    # // "SetAutoConf",
    # // "SetAutoConfTurn",
    # // "SetBlending",
    # // "SetCartAcc",
    "SetCartAngVel",
    "SetCartLinVel",
    "SetCheckpoint",
    "SetConfTurn",
    "SetGripperForce",
    "SetGripperVel",
    "SetJointAcc",
    "SetJointVel",
    # // "SetVelTimeout",
    "EnableEtherNetIP",
    # // "GetModelJointLimits",
    # // "LogTrace",
    # // "SetEOB",
    # // "SetEOM",
    # // "SetJointLimitsCfg",
    # // "SetMonitoringInterval",
    # // "SetOfflineProgramLoop",
    # // "SetRTC",
    # // "StartProgram",
    # // "StartSaving",
    # "TCPDump" 
]

OneArgRequest = [
    "GetJointLimits",
    "GetRtAccelerometer"
]

SixArgCommand = [
    "MoveJoints",
    "MoveJointsVel",
    "MoveLin",
    "MoveLinRelTRF",
    "MoveLinRelWRF",
    "MoveLinVelTRF",
    "MoveLinVelWRF",
    "MovePose",
    "SetTorqueLimit",
    # // "SetTR,
    # // "SetWR,
    # // "SetNetworkOptions"
]